apiVersion: v1
kind: Namespace
metadata:
  name: hotel-service-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: hotelservice-secrets
  namespace: hotel-service-ns
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "pass123"
  DB_NAME: "airbnb_dev"
  HOST_NAME: "mysql"
  REDIS_SERVER_URL: "redis://redis:6379"
